In [1]:
import numpy as np

### 1. Write a function so that the columns of the output matrix are powers of the input vector.
### The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [2]:
inp = np.array([2,4,5,6,7])
def vander_matrix(inp,N,increasing):
    
    if not increasing:
        op = np.array([j**(N-i-1) for j in inp for i in range(N)]).reshape(inp.size,N)
    elif increasing:
        op = np.array([j**i for j in inp for i in range(N)]).reshape(inp.size,N)
    return op



In [3]:
vander_matrix(inp,3,True)        # in increasing sequence

array([[ 1,  2,  4],
       [ 1,  4, 16],
       [ 1,  5, 25],
       [ 1,  6, 36],
       [ 1,  7, 49]])

In [4]:
vander_matrix(inp,4,False)       # in decreasing sequence

array([[  8,   4,   2,   1],
       [ 64,  16,   4,   1],
       [125,  25,   5,   1],
       [216,  36,   6,   1],
       [343,  49,   7,   1]])

### 2. Write a function to find moving average in an array over a window: 
####     Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

##### Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows: The moving average sequence has n-k+1 elements as shown below. The moving averages with k=4 of a ten-value sequence (n=10) is shown below 
###### Input 10 20 30 40 50 60 70 80 90 100
###### y1 :  25 = (10+20+30+40)/4
###### y2 :  35 = (20+30+40+50)/4
###### y3 : 45 = (30+40+50+60)/4
###### y4 : 55 = (40+50+60+70)/4
###### y5 : 65 = (50+60+70+80)/4
###### y6 : 75 = (60+70+80+90)/4
###### y7 : 85 = (70+80+90+100)/4

In [11]:
arr = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k = 3
n = len(arr)
sl = []
for i in range(n):
    if i < (n-k+1):
        s = (sum(arr[i:i+k]))
        sl.append(s)
    ar = np.array(sl)
    ar = np.divide(ar,k)
ar    

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])